version: '3.8'

services:
  mysql-pedidos:
    image: mysql:8.0
    container_name: mysql-pedidos
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pedidos
    ports:
      - "3307:3306"
    networks:
      - micro-net

  pedidos:
    build: ./Microservicio-Pedidos
    container_name: pedidos
    ports:
      - "8081:8080"

    networks:
      - micro-net

networks:
  micro-net:
    driver: bridge