version: '3.8'

services:

  mysql_cliente:          # ← debe llamarse exactamente así
    image: mysql:8.0
    container_name: mysql_cliente
    restart: always
    environment:
      MYSQL_DATABASE: cliente
      MYSQL_USER: juliana
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3309:3306"
    volumes:
      - mysql_cliente_data:/var/lib/mysql
    networks:
      - cliente-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  cliente:
    build: .
    container_name: microservicio_cliente
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-cliente:3306/cliente
      SPRING_DATASOURCE_USERNAME: juliana
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      mysql_cliente:
        condition: service_healthy
    networks:
      - cliente-net

networks:
  cliente-net:
    driver: bridge

volumes:
  mysql_cliente_data: