name: Deploy to Azure VM

on:
  push:
    branches:
      - master  # Ajustado para tu rama master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Azure VM via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          # El script que se ejecutará dentro de tu VM
         script: |
            cd /home/azureuser/
            
            # 1. Detener y ELIMINAR contenedores y redes viejas
            docker-compose down --remove-orphans
            
            # 2. Actualizar el código de Clientes
            cd /home/azureuser/MicroserviciosApp
            git pull origin master || git pull origin main
            
            # 3. Actualizar el código de Pedidos
            cd /home/azureuser/Microservicio
            git pull origin master || git pull origin main
            
            # 4. Volver a la raíz y levantar todo de nuevo
            cd /home/azureuser/
            docker-compose up -d --build
            
            # 5. Limpieza profunda de imágenes y contenedores parados
            docker system prune -f
