name: Deploy to Azure VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Azure VM via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          script: |
            cd /home/azureuser/

            # 1. Detener y eliminar contenedores viejos
            docker-compose down --remove-orphans

            # 2. Actualizar código Clientes
            cd /home/azureuser/MicroserviciosApp
            git pull origin master || git pull origin main

            # 3. Actualizar código Pedidos
            cd /home/azureuser/Microservicio
            git pull origin master || git pull origin main

            # 4. Levantar todo nuevamente
            cd /home/azureuser/
            docker-compose up -d --build

            # 5. Limpieza
            docker system prune -f
            docker-compose up -d --build
            
            # 5. Limpieza profunda de imágenes y contenedores parados
            docker system prune -f
